"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["run.py"]
DATA_FILES = []
OPTIONS = {
    "iconfile": "assets/icon_dark.icns",
    "plist": {
        "CFBundleName": "Quiper",
        "CFBundleIdentifier": "com.github-sassanh.quiper",
        "LSUIElement": True,
        "NSCameraUsageDescription": "Camera access is needed to take pictures.",
        "NSMicrophoneUsageDescription": "Microphone access is needed for voice mode features.",
    },
    "includes": ["pyobjc", "jaraco.text"],
    "packages": ["quiper"],
    "resources": [
        "assets/logo_dark.png",
        "assets/logo_light.png",
    ],
}


setup(
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
